/**
 * Response field schemas for ViciDial API functions.
 * Maps positional pipe-delimited fields to named properties.
 */

// ─── Agent API Response Schemas ──────────────────────────────

export const AGENT_SCHEMAS = {
	external_hangup: ["value", "user"] as const,
	external_status: ["value", "user"] as const,
	external_pause: ["value", "timestamp", "user"] as const,
	external_dial: [
		"phone",
		"user",
		"search",
		"preview",
		"focus",
		"lead_id",
		"timestamp",
		"campaign_id",
		"group_alias",
		"alt_phone",
	] as const,
	preview_dial_action: ["value", "user", "result"] as const,
	external_add_lead: [
		"phone",
		"campaign",
		"list_id",
		"new_lead_id",
		"user",
	] as const,
	change_ingroups: ["blended", "ingroup_list", "user"] as const,
	update_fields: ["user", "lead_id", "timestamp", "field_updates"] as const,
	set_timer_action: ["user", "lead_id", "value", "notes", "rank"] as const,
	st_login_log: ["user_id"] as const,
	st_get_agent_active_lead: [
		"user_id",
		"phone_number",
		"lead_id",
		"vendor_lead_code",
		"province",
		"security_phrase",
		"source_id",
	] as const,
	ra_call_control: ["user", "call_id", "destination"] as const,
	send_dtmf: ["dtmf_string", "user"] as const,
	transfer_conference: [
		"value",
		"ingroup",
		"",
		"consultative",
		"user",
		"call_id",
	] as const,
	park_call: ["value", "user"] as const,
	logout: ["value", "timestamp", "user"] as const,
	recording: [
		"user",
		"action",
		"",
		"",
		"",
		"server",
		"session",
		"status",
	] as const,
	stereo_recording: [
		"user",
		"action",
		"",
		"",
		"",
		"server",
		"session",
		"status",
	] as const,
	recording_status: [
		"user",
		"recording_id",
		"filename",
		"server",
		"start_time",
		"agent_server",
		"session",
		"agent_status",
	] as const,
	stereo_recording_status: [
		"user",
		"recording_id",
		"filename",
		"server",
		"start_time",
		"agent_server",
		"session",
		"agent_status",
	] as const,
	audio_playback: ["filename", "stage", "user"] as const,
	switch_lead: [
		"user",
		"lead_id",
		"vendor_lead_code",
		"campaign",
		"next_lead_id",
	] as const,
	calls_in_queue_count: ["count"] as const,
	force_fronter_leave_3way: ["fronter_user_id"] as const,
	force_fronter_audio_stop: [
		"scope",
		"",
		"fronter_user_id",
		"lead_id",
	] as const,
	send_notification: [] as const,
	vm_message: [
		"user",
		"lead_id",
		"audio_file_1",
		"audio_file_2",
		"audio_file_3",
	] as const,
	refresh_panel: ["user", "timestamp", "refresh_count", "panels"] as const,
	pause_code: ["user"] as const,
} as const;

// ─── Admin API Response Schemas ──────────────────────────────

export const ADMIN_SCHEMAS = {
	// Leads
	add_lead: [
		"phone_number",
		"user",
		"list_id",
		"lead_id",
		"gmt_offset",
	] as const,
	update_lead: ["user", "lead_id"] as const,
	batch_update_lead: ["user", "count", "lead_ids"] as const,
	lead_field_info: ["value"] as const,
	lead_all_info: [
		"status",
		"user",
		"vendor_lead_code",
		"source_id",
		"list_id",
		"gmt_offset_now",
		"phone_code",
		"phone_number",
		"title",
		"first_name",
		"middle_initial",
		"last_name",
		"address1",
		"address2",
		"address3",
		"city",
		"state",
		"province",
		"postal_code",
		"country_code",
		"gender",
		"date_of_birth",
		"alt_phone",
		"email",
		"security_phrase",
		"comments",
		"called_count",
		"last_local_call_time",
		"rank",
		"owner",
		"entry_list_id",
		"lead_id",
	] as const,
	lead_callback_info: [
		"lead_id",
		"callback_type",
		"recipient",
		"callback_status",
		"lead_status",
		"callback_date",
		"entry_date",
		"user",
		"list_id",
		"campaign_id",
		"user_group",
		"customer_timezone",
		"customer_time",
		"comments",
	] as const,
	lead_search: ["search_key", "records_found", "lead_ids"] as const,
	ccc_lead_info: [
		"status",
		"user",
		"vendor_lead_code",
		"source_id",
		"list_id",
		"gmt_offset_now",
		"phone_code",
		"phone_number",
		"title",
		"first_name",
		"middle_initial",
		"last_name",
		"address1",
		"address2",
		"address3",
		"city",
		"state",
		"province",
		"postal_code",
		"country_code",
		"gender",
		"date_of_birth",
		"alt_phone",
		"email",
		"security_phrase",
		"comments",
		"called_count",
		"last_local_call_time",
		"rank",
		"owner",
	] as const,
	callid_info: ["call_id", "custtime"] as const,
	callid_info_detail: [
		"call_id",
		"custtime",
		"call_date",
		"campaign_id",
		"list_id",
		"status",
		"user",
		"phone",
	] as const,
	lead_dearchive: ["user", "lead_id", "insert_count", "delete_count"] as const,

	// Users
	add_user: ["user", "agent_user", "pass", "level", "name", "group"] as const,
	update_user: ["user", "agent_user"] as const,
	copy_user: ["user", "agent_user", "pass", "name", "source_user"] as const,
	update_remote_agent: ["user", "agent_user"] as const,
	user_details: [
		"user",
		"full_name",
		"user_group",
		"user_level",
		"active",
	] as const,
	agent_campaigns: ["user", "allowed_campaigns", "allowed_ingroups"] as const,

	// Monitoring
	agent_status: [
		"status",
		"call_id",
		"lead_id",
		"campaign_id",
		"calls_today",
		"full_name",
		"user_group",
		"user_level",
		"pause_code",
		"real_time_sub_status",
		"phone_number",
		"vendor_lead_code",
		"session_id",
	] as const,
	user_group_status: [
		"usergroups",
		"calls_waiting",
		"agents_logged_in",
		"agents_in_calls",
		"agents_waiting",
		"agents_paused",
		"agents_in_dead_calls",
		"agents_in_dispo",
		"agents_in_dial",
	] as const,
	in_group_status: [
		"ingroups",
		"total_calls",
		"calls_waiting",
		"agents_logged_in",
		"agents_in_calls",
		"agents_waiting",
		"agents_paused",
		"agents_in_dispo",
		"agents_in_dial",
	] as const,

	// Reporting
	recording_lookup: [
		"start_time",
		"user",
		"recording_id",
		"lead_id",
		"location",
	] as const,
	recording_lookup_duration: [
		"start_time",
		"user",
		"recording_id",
		"lead_id",
		"duration",
		"location",
	] as const,
	did_log_export: [
		"did_number",
		"call_date",
		"caller_id_number",
		"length_in_sec",
	] as const,
	agent_stats_export: [
		"user",
		"full_name",
		"user_group",
		"calls",
		"login_time",
		"total_talk_time",
		"avg_talk_time",
		"avg_wait_time",
		"pct_of_queue",
		"pause_time",
		"sessions",
		"avg_session",
		"pauses",
		"avg_pause_time",
		"pause_pct",
		"pauses_per_session",
		"wait_time",
		"talk_time",
		"dispo_time",
		"dead_time",
	] as const,
	phone_number_log: [
		"phone_number",
		"call_date",
		"list_id",
		"length_in_sec",
		"lead_status",
		"hangup_reason",
		"call_status",
		"source_id",
		"user",
	] as const,

	// Phones
	add_phone: [
		"user",
		"extension",
		"server_ip",
		"protocol",
		"dialplan",
	] as const,
	update_phone: ["user", "extension", "server_ip"] as const,
	add_phone_alias: ["user", "alias_id", "alias_name", "phone_logins"] as const,
	update_phone_alias: ["user", "alias_id"] as const,

	// Lists
	list_info: [
		"list_id",
		"list_name",
		"campaign_id",
		"active_leads",
		"dial_level",
		"leads_today",
	] as const,
	list_custom_fields: [
		"list_id",
		"field_label",
		"field_type",
		"field_order",
	] as const,

	// Campaigns
	campaigns_list: [
		"campaign_id",
		"campaign_name",
		"active",
		"user_group",
		"dial_method",
		"dial_level",
		"lead_order",
		"dial_statuses",
		"dial_timeout",
		"dial_prefix",
		"manual_dial_prefix",
		"three_way_dial_prefix",
	] as const,
	hopper_list: [
		"hopper_order",
		"priority",
		"lead_id",
		"list_id",
		"phone_number",
		"phone_code",
		"state",
		"status",
		"count",
		"gmt_offset",
		"rank",
		"alt",
		"hopper_source",
		"vendor_lead_code",
		"source_id",
		"age_days",
		"last_call_time",
	] as const,

	// DIDs
	add_did: ["user", "did_pattern"] as const,
	copy_did: ["user", "source_did_pattern", "count", "errors"] as const,
	update_did: ["user", "did_pattern"] as const,

	// DNC
	add_dnc_phone: ["user", "phone_number", "campaign"] as const,
	delete_dnc_phone: ["user", "phone_number", "campaign"] as const,
	add_fpg_phone: ["user", "phone_number", "group"] as const,
	delete_fpg_phone: ["user", "phone_number", "group"] as const,

	// Monitoring (additional)
	blind_monitor: ["phone_login", "dial_string", "session_id"] as const,
	logged_in_agents: [
		"user",
		"campaign_id",
		"session_id",
		"status",
		"lead_id",
		"callerid",
		"calls_today",
		"full_name",
		"user_group",
		"user_level",
	] as const,
	logged_in_agents_detail: [
		"user",
		"campaign_id",
		"session_id",
		"status",
		"lead_id",
		"callerid",
		"calls_today",
		"full_name",
		"user_group",
		"user_level",
		"pause_code",
		"sub_status",
	] as const,

	// Reporting (additional)
	call_status_stats: [
		"campaign_or_ingroup",
		"total_calls",
		"human_answered_calls",
		"hourly_breakdown",
		"status_breakdown",
	] as const,

	// CID/Aliases
	add_group_alias: [
		"user",
		"caller_id_number",
		"group_alias_id",
		"group_alias_name",
	] as const,
	update_cid_group_entry: [
		"user",
		"cid_group_id",
		"areacode",
		"outbound_cid",
		"entries_affected",
	] as const,

	// Campaign URLs/Presets
	update_alt_url: [
		"user",
		"alt_url_id",
		"url_type",
		"entry_type",
		"campaign_id",
	] as const,
	update_presets: ["user", "preset_id", "entry_type", "campaign_id"] as const,
	hopper_bulk_insert: [
		"inserted_count",
		"not_inserted_count",
		"last_lead_id",
		"user",
	] as const,

	// System
	server_refresh: ["user", "server_count"] as const,

	// Logs
	update_log_entry: [
		"user",
		"agent",
		"campaign",
		"call_id",
		"new_status",
		"old_status",
		"timestamp",
	] as const,
} as const;
